[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
runs = 200
solc = "0.7.6"
#auto_detect_solc = true
evm_version = "istanbul"

[rpc_endpoints]
base = "https://base-mainnet.g.alchemy.com/v2/<your_key>"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/<your_key>"

[etherscan]
base = { key = "<your_key>" }
arbitrum = { key = "<your_key>" }
